config/routes.rb
Rails.application.routes.draw do
  namespace :api , defaults: {format: 'json'} do
    namespace :v1 do
      resources :quotes, :categories, :authors
      get '/favorite/:id', to: 'quotes#favorite'
      get '/quote/hot/', to: 'quotes#hot'
      get '/quote/top/', to: 'quotes#top'

    end
  end
  
  
  resources :quotes
  devise_for :users

  root 'quotes#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :quotes
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :quotes
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	#belongs_to :user
	#has_many :quotes
end

app/models/quote.rb
class Quote < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
  belongs_to :author
  after_initialize :default_values
  
  scope :created_between, lambda {|start_date, end_date| where("created_at >= ? AND created_at <= ?", start_date, end_date )}

  private
    def default_values
      self.favorites ||= 0
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :quotes
  has_many :favorites
  has_many :favorite_quotes, through: :favorites, source: :quotes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/v1/authors_controller.rb
module Api
  module V1
    class AuthorsController < ApplicationController
      skip_before_filter  :verify_authenticity_token
      respond_to :json
      
      def index
        respond_with Author.all
      end
      
      def show
        respond_with Author.find(params[:id])
      end
      
    end
  end
end

app/controllers/api/v1/categories_controller.rb
module Api
  module V1
    class CategoriesController < ApplicationController
      skip_before_filter  :verify_authenticity_token
      respond_to :json
      
      def index
        respond_with Category.all
      end
      
      def show
        respond_with Category.find(params[:id])
      end 
      
    end
  end
end

app/controllers/api/v1/quotes_controller.rb
module Api
  module V1
    class QuotesController < ApplicationController
      skip_before_filter  :verify_authenticity_token
      respond_to :json
      

      def index
        page = params.has_key?(:page)? params[:page] : 1
        per_page = params.has_key?(:limit)? params[:limit] : 25
        mode = params.has_key?(:mode)? params[:mode] : ''
        time = params.has_key?(:t)? params[:t] : 'year'
        
        case(time)
          when 'year'
            start = 1.year.ago
          when 'month'
            start = 1.month.ago
          when 'week'
            start = 1.week.ago
          when 'day'
            start = 1.year.ago
        end
        
        case(mode)
          when "top"         
            quotes = Quote.order('favorites desc')
          when "new"
            quotes = Quote.order('created_at desc')
          else 
            quotes = Quote.order('created_at desc')
        end
        respond_with quotes.created_between(start, Time.now).page(page).per(per_page)
      end
      
     
      
      def show
        respond_with Quote.find(params[:id])
      end
      
      def create
        if !quote_params[:category_id]
          category = Category.where(name: quote_params[:category]).first_or_create
          respond_with Quote.create(text: quote_params[:text], category_id: category.id)
        else
          respond_with Quote.create( quote_params)
        end
      end
      
      def favorite
        quote = Quote.find(params[:id])
        quote.update(favorites: quote.favorites + 1)
        respond_with quote
      end
      

      
      private 
        def quote_params 
          params.require(:quote).permit(:text, :category, :category_id)
        end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
    respond_to do |format|
      format.html
      format.json { render json: @quotes, each_serializer: QuoteSerializer }
    end
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @quote }
    end
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url }
    end
  end
  
  def update
    @quote = Quote.find(params[:id])
    @quote.update(favorites: @quote.favorites + 1)
    respond_with @quote
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Quotes" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= yield :javascript_includes %>
    
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Quotations</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in? %>
            <li><%= link_to "Logged in as #{current_user.email}" %><li>
            <li><%= link_to 'Edit profile', edit_user_registration_path %><li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %><li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path %><li>
            <li><%= link_to "Login", new_user_session_path %><li>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </head>
  <body>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div><!--/row-->



    </div> <!-- /container -->

  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_for @quote, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :text, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                quotes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<div class="box" id="DIV_1">
    <div id="DIV_4"  style="background: #<%=quote.color%>">
        <p id="P_5">"<%= quote.text %>"</p>
        <p id="P_6"> — via <a href="<%= quote_path(quote) %>" id="A_7">unknown</a></p>
        <div id="DIV_9">	<a><i class="fa fa-heart"></i></a>  </div>
    </div>
</div>

app/views/quotes/edit.html.erb
<%- model_class = Quote -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quotes/index.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "masonry.js" %>
<% end %>

<% content_for :css do  %>

<% end %>

<%- model_class = Quote -%>


<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
    <% @quotes.each do |quote| %>
        <%= render quote %>
    <% end %>
</div>

app/views/quotes/new.html.erb
<%- model_class = Quote -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quotes/show.html.erb
<%- model_class = Quote -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:text) %>:</strong></dt>
  <dd><%= @quote.text %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              quotes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_quote_path(@quote), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              quote_path(@quote),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>